# Generated by Django 6.0.4 on 2026-04-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyIdMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_table', models.CharField(max_length=64)),
                ('legacy_id', models.BigIntegerField()),
                ('new_id', models.BigIntegerField()),
                ('organization_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'etl_legacy_id_map',
                'indexes': [models.Index(fields=['legacy_table', 'new_id'], name='etl_legacy__legacy__313c7e_idx')],
                'constraints': [models.UniqueConstraint(fields=('legacy_table', 'legacy_id', 'organization_id'), name='etl_legacy_id_map_unique_per_scope')],
            },
        ),
    ]
