# Generated by Django 6.0.4 on 2026-04-20 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('duration_days', models.PositiveIntegerField()),
                ('price_minor_units', models.BigIntegerField(help_text='Integer count of minor currency units.')),
                ('currency_code', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'billing_plan',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_days__gt', 0)), name='billing_plan_duration_positive'), models.CheckConstraint(condition=models.Q(('price_minor_units__gte', 0)), name='billing_plan_price_non_negative')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenancy.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.plan')),
            ],
            options={
                'db_table': 'billing_subscription',
                'ordering': ('organization_id', '-period_end'),
                'indexes': [models.Index(fields=['organization', 'period_end'], name='billing_sub_organiz_4f9de0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('period_end__gt', models.F('period_start'))), name='billing_subscription_period_end_after_start')],
            },
        ),
    ]
