# Generated by Django 6.0.4 on 2026-04-22 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_audit_fields'),
        ('treasury', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='bankreconciliation',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='bankstatement',
            options={'ordering': ('-statement_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='bankstatementline',
            options={'ordering': ('statement_id', 'sequence')},
        ),
        migrations.AlterModelOptions(
            name='cashbox',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='treasurytransaction',
            options={'ordering': ('-transaction_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='treasurytransfer',
            options={'ordering': ('-transfer_date', '-id')},
        ),
        migrations.RenameIndex(
            model_name='treasurytransaction',
            new_name='treasury_tr_organiz_73c3cf_idx',
            old_name='treasury_txn_org_date_idx',
        ),
        migrations.RenameIndex(
            model_name='treasurytransaction',
            new_name='treasury_tr_organiz_30d571_idx',
            old_name='treasury_txn_org_status_idx',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='cashbox',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='treasurytransaction',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='treasurytransfer',
            name='branch',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbox',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasurytransaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasurytransfer',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='treasurytransfer',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='gl_account',
            field=models.ForeignKey(help_text='GL asset account that represents this bank account.', on_delete=django.db.models.deletion.PROTECT, related_name='treasury_bank_accounts', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bankreconciliation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bankstatementline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='gl_account',
            field=models.ForeignKey(help_text='GL asset account that represents this cashbox.', on_delete=django.db.models.deletion.PROTECT, related_name='cashboxes', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='cashbox',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='requires_reference',
            field=models.BooleanField(default=False, help_text='If True, a reference number is required (e.g. cheque number, transfer ref).'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='contra_account',
            field=models.ForeignKey(help_text='The GL account on the other side of the entry.', on_delete=django.db.models.deletion.PROTECT, related_name='treasury_contra_transactions', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='treasurytransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='treasurytransfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='treasurytransfer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
