# Generated by Django 6.0.4 on 2026-04-23 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasury', '0002_add_audit_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(('debit_amount__gte', 0)), name='treasury_stmt_line_debit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(('credit_amount__gte', 0)), name='treasury_stmt_line_credit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bankstatementline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_amount', 0), ('debit_amount__gt', 0)), models.Q(('credit_amount__gt', 0), ('debit_amount', 0)), models.Q(('credit_amount', 0), ('debit_amount', 0)), _connector='OR'), name='treasury_stmt_line_not_both_sides'),
        ),
    ]
