# Generated by Django 6.0.4 on 2026-04-22 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hrms_extended'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeebenefit',
            new_name='hr_employee_organiz_490a35_idx',
            old_name='hr_empbenefit_organiz_idx',
        ),
        migrations.RenameIndex(
            model_name='employeeevaluation',
            new_name='hr_employee_organiz_88a773_idx',
            old_name='hr_eval_organiz_emp_year_idx',
        ),
        migrations.RenameIndex(
            model_name='employeetraining',
            new_name='hr_employee_organiz_a62af9_idx',
            old_name='hr_training_organiz_emp_idx',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='hr_leave_re_organiz_980d94_idx',
            old_name='hr_leavereq_organiz_idx1',
        ),
        migrations.RenameIndex(
            model_name='leaverequest',
            new_name='hr_leave_re_organiz_6c0c0f_idx',
            old_name='hr_leavereq_organiz_idx2',
        ),
        migrations.AlterField(
            model_name='employeebenefit',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text="Monthly benefit value in employee's salary currency.", max_digits=18),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='goals_met_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage of goals achieved (0-100).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeevaluation',
            name='period_quarter',
            field=models.PositiveSmallIntegerField(help_text='1-4; use 0 for annual review.'),
        ),
        migrations.AlterField(
            model_name='employeetraining',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Score out of 100.', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='jobtitle',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Seniority level (1=junior).'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_days_per_year',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = unlimited.'),
        ),
    ]
