# Generated by Django 6.0.4 on 2026-04-20 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='finance.expensecategory')),
            ],
            options={
                'db_table': 'finance_expense_category',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('expense_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('description', models.TextField(blank=True, default='')),
                ('expense_account', models.ForeignKey(help_text='The debit side: an account of type EXPENSE.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses_as_expense_account', to='finance.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('payment_account', models.ForeignKey(help_text='The credit side: typically a cash or bank asset account.', on_delete=django.db.models.deletion.PROTECT, related_name='expenses_as_payment_account', to='finance.account')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.expensecategory')),
            ],
            options={
                'db_table': 'finance_expense',
                'ordering': ('-expense_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('transfer_date', models.DateField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('note', models.TextField(blank=True, default='')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='finance.account')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='money_transfer', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('to_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='finance.account')),
            ],
            options={
                'db_table': 'finance_money_transfer',
                'ordering': ('-transfer_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('card', 'Card'), ('paypal', 'PayPal'), ('giftcard', 'Gift Card'), ('bank_transfer', 'Bank Transfer'), ('other', 'Other')], max_length=16)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=16)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, default='')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_payment',
                'ordering': ('-id',),
            },
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='finance_expense_category_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='finance_expense_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='moneytransfer',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='finance_money_transfer_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='moneytransfer',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_money_transfer_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='moneytransfer',
            constraint=models.CheckConstraint(condition=models.Q(('from_account', models.F('to_account')), _negated=True), name='finance_money_transfer_distinct_accounts'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'source_type', 'source_id'], name='finance_pay_organiz_d637f7_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'method', 'status'], name='finance_pay_organiz_cb55f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='finance_payment_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='finance_payment_amount_positive'),
        ),
    ]
