# Generated by Django 6.0.4 on 2026-04-22 00:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_report_models'),
        ('tenancy', '0003_organization_phase12_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjustmententry',
            options={'ordering': ('-period_id', 'entry_type')},
        ),
        migrations.AlterModelOptions(
            name='closingchecklistitem',
            options={'ordering': ('checklist_id', 'item_key')},
        ),
        migrations.AlterModelOptions(
            name='closingrun',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='periodsignoff',
            options={'ordering': ('-signed_at',)},
        ),
        migrations.AlterModelOptions(
            name='reportline',
            options={'ordering': ('report_type', 'sort_order', 'id')},
        ),
        migrations.AlterModelOptions(
            name='taxtransaction',
            options={'ordering': ('-txn_date', '-id')},
        ),
        migrations.RenameIndex(
            model_name='account',
            new_name='finance_acc_organiz_cc1cfd_idx',
            old_name='finance_acc_org_postable_active_idx',
        ),
        migrations.RenameIndex(
            model_name='journalentry',
            new_name='finance_jou_organiz_b076c5_idx',
            old_name='finance_jou_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='taxtransaction',
            new_name='finance_tax_organiz_35da84_idx',
            old_name='fin_taxtxn_org_date_dir_idx',
        ),
        migrations.RenameIndex(
            model_name='taxtransaction',
            new_name='finance_tax_organiz_85e8dc_idx',
            old_name='fin_taxtxn_org_code_date_idx',
        ),
        migrations.RenameIndex(
            model_name='taxtransaction',
            new_name='finance_tax_organiz_3823fc_idx',
            old_name='fin_taxtxn_org_source_idx',
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='accountreportmapping',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='accountreportmapping',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='adjustmententry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='adjustmententry',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adjustmententry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='adjustmententry',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='closingchecklist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='closingchecklist',
            name='is_complete',
            field=models.BooleanField(default=False, help_text='True when all items are marked done. Set by the use case.'),
        ),
        migrations.AlterField(
            model_name='closingchecklist',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='closingchecklistitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='closingchecklistitem',
            name='item_key',
            field=models.CharField(help_text="Machine key, e.g. 'bank_recs_done'. Unique within a checklist.", max_length=64),
        ),
        migrations.AlterField(
            model_name='closingchecklistitem',
            name='label',
            field=models.CharField(help_text='Human-readable description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='closingchecklistitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='closingrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='closingrun',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='closingrun',
            name='net_income',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net income transferred to retained earnings during this close.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='closingrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='closingrun',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='periodsignoff',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='periodsignoff',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='is_subtotal',
            field=models.BooleanField(default=False, help_text='True for calculated/subtotal lines that do not map directly to accounts.'),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='label',
            field=models.CharField(help_text='Human-readable line description.', max_length=255),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='negate',
            field=models.BooleanField(default=False, help_text='Flip the sign of the aggregated balance (e.g. expenses displayed as positive).'),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent subtotal line, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.reportline'),
        ),
        migrations.AlterField(
            model_name='reportline',
            name='section',
            field=models.CharField(help_text="Section heading, e.g. 'Revenue', 'Cost of Sales', 'Current Assets'.", max_length=128),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='tax_account',
            field=models.ForeignKey(blank=True, help_text='Legacy single GL account. Prefer output_tax_account / input_tax_account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='taxtransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
    ]
