# Generated by Django 6.0.4 on 2026-04-23 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_audit_fields'),
        ('tenancy', '0003_organization_phase12_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('entry_number__gt', '')), fields=('organization', 'entry_number'), name='finance_journal_entry_unique_entry_number_per_org'),
        ),
    ]
