# Generated by Django 6.0.4 on 2026-04-24 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_qa_fixes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxcode',
            name='tax_account',
            field=models.ForeignKey(blank=True, help_text='Deprecated. Prefer output_tax_account / input_tax_account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='finance.account'),
        ),
    ]
