# Generated by Django 6.0.4 on 2026-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_taxcode_tax_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text='Rate from line currency to org functional currency at posting time.', max_digits=18),
        ),
        migrations.AddField(
            model_name='journalline',
            name='functional_credit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Credit converted to org functional currency (credit × exchange_rate).', max_digits=18),
        ),
        migrations.AddField(
            model_name='journalline',
            name='functional_debit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Debit converted to org functional currency (debit × exchange_rate).', max_digits=18),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='jurisdiction_code',
            field=models.CharField(blank=True, default='', help_text="Tax jurisdiction identifier for US sales tax (e.g. 'US-CA-06037'). Blank for flat/VAT codes.", max_length=32),
        ),
    ]
