# Generated by Django 6.0.4 on 2026-04-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_journalline_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=16),
        ),
    ]
