# Generated by Django 6.0.4 on 2026-04-20 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        ('finance', '0002_expensecategory_expense_moneytransfer_payment_and_more'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('purchase_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('posted', 'Posted'), ('received', 'Received'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='draft', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overpaid', 'Overpaid')], db_index=True, default='unpaid', max_length=16)),
                ('currency_code', models.CharField(max_length=3)),
                ('total_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_discount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_tax', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('order_discount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('shipping', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('memo', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='crm.supplier')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases_purchase',
                'ordering': ('-purchase_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_discount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_tax', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchase')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'purchases_purchase_line',
                'ordering': ('purchase_id', 'line_number'),
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'supplier', 'purchase_date'], name='purchases_p_organiz_200bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['organization', 'status', 'purchase_date'], name='purchases_p_organiz_c722b5_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='purchases_purchase_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='purchases_purchase_grand_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.UniqueConstraint(fields=('purchase', 'line_number'), name='purchases_line_unique_line_number_per_purchase'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchases_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='purchases_line_unit_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100), ('tax_rate_percent__gte', 0), ('tax_rate_percent__lte', 100)), name='purchases_line_percentages_in_range'),
        ),
    ]
