# Generated by Django 6.0.4 on 2026-04-20 18:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        ('finance', '0002_expensecategory_expense_moneytransfer_payment_and_more'),
        ('inventory', '0002_stockadjustment_stockadjustmentline_stockcount_and_more'),
        ('purchases', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='returned_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.CreateModel(
            name='PurchaseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('return_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('currency_code', models.CharField(max_length=3)),
                ('lines_subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_discount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_tax', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('refund_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('memo', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('original_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchase')),
                ('reversal_journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return', to='finance.journalentry')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_returns', to='crm.supplier')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchases_purchase_return',
                'ordering': ('-return_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_discount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_tax', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('movement_id', models.BigIntegerField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('original_purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='purchases.purchaseline')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_lines', to='catalog.product')),
                ('purchase_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchases.purchasereturn')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_lines', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'purchases_purchase_return_line',
                'ordering': ('purchase_return_id', 'line_number'),
            },
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['organization', 'original_purchase'], name='purchases_p_organiz_97141f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasereturn',
            index=models.Index(fields=['organization', 'status', 'return_date'], name='purchases_p_organiz_6ed1ee_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='purchases_purchase_return_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturn',
            constraint=models.CheckConstraint(condition=models.Q(('refund_total__gte', 0)), name='purchases_purchase_return_refund_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.UniqueConstraint(fields=('purchase_return', 'line_number'), name='purchases_purchase_return_line_unique_line_number'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchases_purchase_return_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchasereturnline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100), ('tax_rate_percent__gte', 0), ('tax_rate_percent__lte', 100)), name='purchases_purchase_return_line_percentages_in_range'),
        ),
    ]
