# Generated by Django 6.0.4 on 2026-04-22 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_supplier_currency_code_and_more'),
        ('finance', '0010_add_audit_fields'),
        ('purchases', '0003_phase3_payables'),
        ('tenancy', '0003_organization_phase12_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ('-invoice_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoiceline',
            options={'ordering': ('invoice_id', 'sequence')},
        ),
        migrations.AlterModelOptions(
            name='vendorcreditnote',
            options={'ordering': ('-note_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='vendorcreditnoteline',
            options={'ordering': ('credit_note_id', 'sequence')},
        ),
        migrations.AlterModelOptions(
            name='vendordebitnote',
            options={'ordering': ('-note_date', '-id')},
        ),
        migrations.AlterModelOptions(
            name='vendordebitnoteline',
            options={'ordering': ('debit_note_id', 'sequence')},
        ),
        migrations.AlterModelOptions(
            name='vendorpayment',
            options={'ordering': ('-payment_date', '-id')},
        ),
        migrations.RenameIndex(
            model_name='purchaseinvoice',
            new_name='purchases_p_organiz_0180f1_idx',
            old_name='purchases_pinv_org_vendor_date',
        ),
        migrations.RenameIndex(
            model_name='purchaseinvoice',
            new_name='purchases_p_organiz_91f62d_idx',
            old_name='purchases_pinv_org_status_due',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcreditnote',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorcreditnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendordebitnote',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendordebitnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total payments + credit notes applied to this invoice.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='due_date',
            field=models.DateField(help_text='Payment due date. Must be ≥ invoice_date.'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text="Rate of this invoice's currency to the org's functional currency.", max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Sequential number assigned on issue (e.g. PINV-2026-000001).', max_length=32),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='vendor_invoice_number',
            field=models.CharField(blank=True, default='', help_text="The supplier's own invoice/reference number.", max_length=64),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='Expense/purchases GL account for this line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorcreditnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendorcreditnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorcreditnoteline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendorcreditnoteline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendordebitnote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendordebitnote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendordebitnoteline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendordebitnoteline',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='bank_account',
            field=models.ForeignKey(help_text='Cash/Bank GL account debited on payment.', on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorpayment',
            name='payment_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Sequential number assigned on post (e.g. VPAY-2026-000001).', max_length=32),
        ),
        migrations.AlterField(
            model_name='vendorpaymentallocation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='vendorpaymentallocation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['organization', 'vendor', 'payment_date'], name='purchases_v_organiz_b821f9_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorpayment',
            index=models.Index(fields=['organization', 'status'], name='purchases_v_organiz_62d37a_idx'),
        ),
    ]
