# Generated by Django 6.0.4 on 2026-04-23 21:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_supplier_currency_code_and_more'),
        ('finance', '0011_qa_fixes'),
        ('purchases', '0004_alter_purchaseinvoice_options_and_more'),
        ('tenancy', '0003_organization_phase12_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='purchaseinvoice',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice_number__gt', '')), fields=('organization', 'invoice_number'), name='purchases_pinv_unique_number_per_org'),
        ),
    ]
