# Generated by Django 6.0.4 on 2026-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_pinv_unique_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Computed withholding tax amount deducted from payment.', max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='withholding_tax_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Withholding tax rate applied at payment (e.g. 5 for 5%). 0 = none.', max_digits=6),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='depreciation_method',
            field=models.CharField(blank=True, choices=[('straight_line', 'Straight-Line'), ('declining_balance', 'Declining Balance'), ('sum_of_years', 'Sum-of-Years-Digits')], default='', help_text='Depreciation method. Required when is_capitalized=True.', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='is_capitalized',
            field=models.BooleanField(default=False, help_text='True = capital expenditure (depreciated over time); False = immediate expense.'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='useful_life_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Useful life in months for straight-line depreciation. Required when is_capitalized=True.', null=True),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='withholding_tax_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount withheld from this payment and remitted to tax authority.', max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='withholding_tax_percent',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Withholding rate applied to this payment (overrides invoice rate if set).', max_digits=6),
        ),
    ]
