# Generated by Django 6.0.4 on 2026-04-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_journalline_exchange_rate_and_more'),
        ('purchases', '0006_purchaseinvoice_withholding_tax_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text="Rate of this payment's currency to the org's functional currency.", max_digits=18),
        ),
        migrations.AddField(
            model_name='vendorpayment',
            name='withholding_tax_account',
            field=models.ForeignKey(blank=True, help_text='Withholding Tax Payable GL account. Required when withholding_tax_amount > 0.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withholding_vendor_payments', to='finance.account'),
        ),
    ]
