# Generated by Django 6.0.4 on 2026-04-24 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_supplier_is_1099_vendor'),
        ('finance', '0013_journalline_exchange_rate_and_more'),
        ('purchases', '0007_vpay_withholding_account_exchange_rate'),
        ('tenancy', '0005_organization_accounting_standard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDebitNoteAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'purchases_vendor_debit_note_allocation',
            },
        ),
        migrations.AddField(
            model_name='vendordebitnote',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Total vendor payments applied against this debit note.', max_digits=18),
        ),
        migrations.AddConstraint(
            model_name='vendordebitnote',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gte', 0)), name='purchases_vdn_allocated_non_negative'),
        ),
        migrations.AddField(
            model_name='vendordebitnoteallocation',
            name='debit_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='purchases.vendordebitnote'),
        ),
        migrations.AddField(
            model_name='vendordebitnoteallocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='vendordebitnoteallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_allocations', to='purchases.vendorpayment'),
        ),
        migrations.AddConstraint(
            model_name='vendordebitnoteallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'debit_note'), name='purchases_vdn_alloc_unique_payment_debit_note'),
        ),
        migrations.AddConstraint(
            model_name='vendordebitnoteallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_amount__gt', 0)), name='purchases_vdn_alloc_amount_positive'),
        ),
    ]
