# Generated by Django 6.0.4 on 2026-04-25 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_pinv_line_quantity_received'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchaseinvoice',
            name='purchases_pinv_allocated_not_exceeds_total',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinvoice',
            name='purchases_pinv_exchange_rate_positive',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinvoice',
            name='purchases_pinv_wht_percent_in_range',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinvoice',
            name='purchases_pinv_wht_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinvoiceline',
            name='purchases_pinv_line_tax_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='purchaseinvoiceline',
            name='purchases_pinv_line_discount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='vendorpayment',
            name='purchases_vpay_allocated_not_exceeds_amount',
        ),
        migrations.RemoveConstraint(
            model_name='vendorpayment',
            name='purchases_vpay_exchange_rate_positive',
        ),
        migrations.RemoveConstraint(
            model_name='vendorpayment',
            name='purchases_vpay_wht_percent_in_range',
        ),
        migrations.RemoveConstraint(
            model_name='vendorpayment',
            name='purchases_vpay_wht_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='vendorpayment',
            name='purchases_vpay_wht_amount_not_exceeds_payment',
        ),
        migrations.RemoveConstraint(
            model_name='vendorpayment',
            name='purchases_vpay_wht_account_required_when_wht_nonzero',
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('credited', 'Credited')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceline',
            name='quantity_received',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cumulative quantity physically received into stock. Incremented on invoice issue.', max_digits=18),
        ),
    ]
