# Generated by Django 6.0.4 on 2026-04-20 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0002_expensecategory_expense_moneytransfer_payment_and_more'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Default discount applied on sales for members.', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'crm_customer_group',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('tax_number', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='crm.customergroup')),
            ],
            options={
                'db_table': 'crm_customer',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to='crm.customer')),
                ('liability_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_wallets', to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'crm_customer_wallet',
            },
        ),
        migrations.CreateModel(
            name='CustomerWalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('deposit', 'Deposit'), ('redeem', 'Redeem'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('signed_delta', models.DecimalField(decimal_places=4, help_text='+amount for deposits / refunds; -amount for redemptions; signed for adjustments.', max_digits=18)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('memo', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wallet_transaction', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='crm.customerwallet')),
            ],
            options={
                'db_table': 'crm_customer_wallet_transaction',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('tax_number', models.CharField(blank=True, default='', max_length=64)),
                ('note', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'crm_supplier',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Biller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('address_line1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line2', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=128)),
                ('state', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=32)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('tax_number', models.CharField(blank=True, default='', max_length=64)),
                ('logo', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'crm_biller',
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'code'), name='crm_biller_unique_code_per_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='crm_customer_group_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='customergroup',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100)), name='crm_customer_group_discount_in_range'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'phone'], name='crm_custome_organiz_a63938_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'email'], name='crm_custome_organiz_9a10b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='crm_customer_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='customerwallet',
            constraint=models.UniqueConstraint(fields=('customer', 'currency_code'), name='crm_customer_wallet_unique_currency_per_customer'),
        ),
        migrations.AddConstraint(
            model_name='customerwallet',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='crm_customer_wallet_balance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='customerwallettransaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'reference'), name='crm_wallet_tx_unique_reference_per_wallet'),
        ),
        migrations.AddConstraint(
            model_name='customerwallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='crm_wallet_tx_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='crm_supplier_unique_code_per_org'),
        ),
    ]
