# Generated by Django 6.0.4 on 2026-04-22 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_supplier_phase3_fields'),
        ('finance', '0010_add_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='currency_code',
            field=models.CharField(blank=True, default='', help_text="Supplier's functional currency. Blank = use org default.", max_length=3),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='default_expense_account',
            field=models.ForeignKey(blank=True, help_text="Default expense/purchases GL account for this supplier's invoices.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_expenses', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='legal_name',
            field=models.CharField(blank=True, default='', help_text='Official registered name', max_length=256),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name_ar',
            field=models.CharField(blank=True, default='', help_text='Arabic name', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name_en',
            field=models.CharField(blank=True, default='', help_text='English name', max_length=128),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payable_account',
            field=models.ForeignKey(blank=True, help_text='Accounts-payable GL account for this supplier.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supplier_payables', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms_days',
            field=models.PositiveSmallIntegerField(default=30, help_text='Number of days until invoice is due.'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_profile',
            field=models.ForeignKey(blank=True, help_text="Default tax profile applied to this supplier's invoices.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='finance.taxprofile'),
        ),
    ]
