# Generated by Django 6.0.4 on 2026-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_supplier_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='building_number',
            field=models.CharField(blank=True, default='', help_text='Building/unit number — required by ZATCA XML buyer address.', max_length=16),
        ),
        migrations.AddField(
            model_name='customer',
            name='commercial_registration_number',
            field=models.CharField(blank=True, default='', help_text='Commercial registration number — required for ZATCA B2B invoices.', max_length=64),
        ),
        migrations.AlterField(
            model_name='customer',
            name='tax_number',
            field=models.CharField(blank=True, default='', help_text='VAT registration / tax ID. For SA: 15-digit ZATCA number.', max_length=64),
        ),
    ]
