# Generated by Django 6.0.4 on 2026-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_1099_vendor',
            field=models.BooleanField(default=False, help_text='USA: True if this supplier requires a 1099-NEC/1099-MISC at year-end.'),
        ),
    ]
