# Generated by Django 6.0.4 on 2026-04-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0003_organization_phase12_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address_building_number',
            field=models.CharField(blank=True, default='', help_text='Building/unit number — required by ZATCA XML seller address.', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_postal_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organization',
            name='commercial_registration_number',
            field=models.CharField(blank=True, default='', help_text='Commercial registration / company number (required for ZATCA XML seller node).', max_length=64),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_number',
            field=models.CharField(blank=True, default='', help_text='VAT/GST registration number. For SA: 15-digit ZATCA number. For US: EIN (XX-XXXXXXX).', max_length=64),
        ),
    ]
