# Generated by Django 6.0.4 on 2026-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0004_organization_address_building_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='accounting_standard',
            field=models.CharField(blank=True, choices=[('ifrs', 'IFRS'), ('ifrs_sme', 'IFRS for SMEs'), ('us_gaap', 'US GAAP'), ('local_sa', 'Local SA Standards')], default='', help_text='Accounting standard used for financial reporting.', max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_system',
            field=models.CharField(blank=True, choices=[('sa_vat', 'Saudi Arabia VAT (ZATCA)'), ('us_sales_tax', 'US Sales Tax'), ('eu_vat', 'EU VAT'), ('none', 'No Tax')], default='', help_text='Tax regime that drives tax code defaults and ZATCA submission.', max_length=16),
        ),
    ]
