# Generated by Django 5.2.13 on 2026-04-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0005_organization_accounting_standard_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="email_host",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_port",
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_encryption",
            field=models.CharField(
                blank=True,
                choices=[("tls", "TLS"), ("ssl", "SSL"), ("none", "None")],
                default="tls",
                help_text="SMTP encryption mode used when sending email (TLS/SSL/None).",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_host_user",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_host_password",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_from_address",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="organization",
            name="email_from_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="sms_gateway",
            field=models.CharField(
                blank=True,
                choices=[("", "Disabled"), ("twilio", "Twilio"), ("clickatell", "Clickatell")],
                default="",
                help_text="SMS gateway used for outbound messages.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="twilio_account_sid",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="organization",
            name="twilio_auth_token",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="organization",
            name="twilio_number",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="clickatell_api_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]

