# Generated by Django 6.0.4 on 2026-04-24 12:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0003_organization_phase12_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZATCAInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(help_text="Model label, e.g. 'sales.salesinvoice', 'sales.creditnote'.", max_length=80)),
                ('source_id', models.PositiveIntegerField()),
                ('invoice_type', models.CharField(choices=[('388_0100', 'Standard Tax Invoice (B2B)'), ('388_0200', 'Simplified Tax Invoice (B2C)'), ('381_0100', 'Credit Note (B2B)'), ('381_0200', 'Credit Note (B2C)'), ('383_0100', 'Debit Note (B2B)'), ('383_0200', 'Debit Note (B2C)')], max_length=10)),
                ('invoice_uuid', models.UUIDField(default=uuid.uuid4, help_text='UUID v4 — ZATCA requires a unique UUID per invoice.', unique=True)),
                ('invoice_counter_value', models.PositiveIntegerField(help_text='ICV — sequential number across ALL invoices for this org.')),
                ('previous_invoice_hash', models.CharField(help_text='PIH — SHA-256 Base64 hash of the immediately preceding invoice.', max_length=256)),
                ('invoice_hash', models.CharField(blank=True, help_text="SHA-256 Base64 hash of this invoice's signed XML.", max_length=256)),
                ('signed_xml', models.TextField(blank=True, help_text='Signed UBL 2.1 XML ready for submission to ZATCA.')),
                ('qr_code_tlv', models.TextField(blank=True, help_text='Base64-encoded TLV QR code payload.')),
                ('status', models.CharField(choices=[('pending', 'Pending Submission'), ('submitted', 'Submitted'), ('cleared', 'Cleared (B2B)'), ('reported', 'Reported (B2C)'), ('warning', 'Accepted with Warnings'), ('rejected', 'Rejected by ZATCA'), ('error', 'Submission Error')], db_index=True, default='pending', max_length=12)),
                ('submission_attempts', models.PositiveSmallIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('zatca_response_json', models.JSONField(blank=True, help_text='Raw response body from ZATCA API.', null=True)),
                ('cleared_invoice_xml', models.TextField(blank=True, help_text='For B2B clearance: ZATCA returns the invoice XML stamped with their signature.')),
                ('error_message', models.TextField(blank=True, help_text='Last error message if status=error.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'ZATCA Invoice',
                'verbose_name_plural': 'ZATCA Invoices',
            },
        ),
        migrations.CreateModel(
            name='ZATCALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(help_text="e.g. 'clearance', 'reporting', 'onboard'.", max_length=60)),
                ('request_url', models.URLField(max_length=512)),
                ('request_body_hash', models.CharField(blank=True, help_text='SHA-256 hex of request body — avoids storing full XML in the log.', max_length=64)),
                ('http_status', models.PositiveSmallIntegerField(null=True)),
                ('response_json', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('error_detail', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('zatca_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='zatca.zatcainvoice')),
            ],
            options={
                'verbose_name': 'ZATCA Log',
                'verbose_name_plural': 'ZATCA Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ZATCACredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox (Developer Portal)'), ('simulation', 'Simulation'), ('production', 'Production')], default='simulation', max_length=12)),
                ('binary_security_token', models.TextField(help_text='Base64-encoded CSID returned by ZATCA /compliance or /production/csids.')),
                ('secret', models.CharField(help_text='Secret returned alongside the CSID.  Treat as a password.', max_length=512)),
                ('private_key_pem', models.TextField(help_text='ECDSA secp256k1 private key (PKCS#8 PEM).  Keep secret.')),
                ('certificate_pem', models.TextField(blank=True, help_text='Decoded CSID as a PEM certificate (for verification use).')),
                ('compliance_request_id', models.CharField(blank=True, help_text='requestID returned by /compliance — needed to obtain production CSID.', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'verbose_name': 'ZATCA Credentials',
                'verbose_name_plural': 'ZATCA Credentials',
                'unique_together': {('organization', 'environment')},
            },
        ),
        migrations.AddIndex(
            model_name='zatcainvoice',
            index=models.Index(fields=['organization', 'status'], name='zatca_zatca_organiz_d11006_idx'),
        ),
        migrations.AddIndex(
            model_name='zatcainvoice',
            index=models.Index(fields=['organization', 'invoice_counter_value'], name='zatca_zatca_organiz_6f7a96_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='zatcainvoice',
            unique_together={('organization', 'source_type', 'source_id')},
        ),
    ]
