# Generated by Django 6.0.4 on 2026-04-24 13:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zatca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zatcainvoice',
            name='invoice_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, help_text='UUID v4 — ZATCA requires a unique UUID per invoice.'),
        ),
    ]
