# Generated by Django 6.0.4 on 2026-04-20 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('currency_code', models.CharField(max_length=3)),
                ('opening_float', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('closing_float', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('expected_cash', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('is_open', models.BooleanField(db_index=True, default=True)),
                ('note', models.TextField(blank=True, default='')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_sessions', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='register_sessions', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'pos_cash_register_session',
                'ordering': ('-opened_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('user', 'warehouse'), name='pos_register_one_open_per_user_warehouse'), models.CheckConstraint(condition=models.Q(('opening_float__gte', 0)), name='pos_register_opening_float_non_negative'), models.CheckConstraint(condition=models.Q(models.Q(('is_open', True), ('closed_at__isnull', True)), models.Q(('is_open', False), ('closed_at__isnull', False)), _connector='OR'), name='pos_register_closed_at_matches_is_open')],
            },
        ),
    ]
