# Generated by Django 6.0.4 on 2026-04-20 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('object_type', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.BigIntegerField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'audit_event',
                'ordering': ('-id',),
                'indexes': [models.Index(fields=['organization', 'event_type', 'created_at'], name='audit_event_organiz_1b8f97_idx'), models.Index(fields=['organization', 'object_type', 'object_id'], name='audit_event_organiz_b926ea_idx')],
            },
        ),
    ]
