# Generated by Django 6.0.4 on 2026-04-20 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='tenancy.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'inventory_warehouse',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StockOnHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_on_hand', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_on_hand', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_on_hand',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In'), ('adjustment', 'Adjustment')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('source_type', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('transfer_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('adjustment_sign', models.SmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_movement',
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='inventory_warehouse_unique_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='stockonhand',
            index=models.Index(fields=['organization', 'warehouse'], name='inventory_s_organiz_bfb994_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockonhand',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='inventory_soh_unique_product_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='stockonhand',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_soh_quantity_non_negative'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'product', 'warehouse', 'occurred_at'], name='inventory_s_organiz_978c06_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'source_type', 'source_id'], name='inventory_s_organiz_036181_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_stock_movement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'adjustment'), ('adjustment_sign__in', [-1, 1])), models.Q(models.Q(('movement_type', 'adjustment'), _negated=True), ('adjustment_sign', 0)), _connector='OR'), name='inventory_stock_movement_adjustment_sign_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ['transfer_in', 'transfer_out']), ('transfer_id__isnull', False)), models.Q(models.Q(('movement_type__in', ['transfer_in', 'transfer_out']), _negated=True), ('transfer_id__isnull', True)), _connector='OR'), name='inventory_stock_movement_transfer_id_matches_type'),
        ),
    ]
