# Generated by Django 6.0.4 on 2026-04-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('adjustment_date', models.DateField(db_index=True)),
                ('reason', models.CharField(choices=[('shrinkage', 'Shrinkage / theft'), ('damage', 'Damage / spoilage'), ('write_off', 'Write-off'), ('correction', 'Clerical correction'), ('other', 'Other')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('memo', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment',
                'ordering': ('-adjustment_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signed_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('movement_id', models.BigIntegerField(blank=True, null=True)),
                ('line_number', models.PositiveIntegerField(default=0)),
                ('adjustment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockadjustment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'db_table': 'inventory_stock_adjustment_line',
                'ordering': ('adjustment_id', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('count_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalised', 'Finalised'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('memo', models.TextField(blank=True, default='')),
                ('finalised_at', models.DateTimeField(blank=True, null=True)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_counts', to='inventory.stockadjustment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_counts', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_count',
                'ordering': ('-count_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expected_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('counted_quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('line_number', models.PositiveIntegerField(default=0)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stockcount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
            ],
            options={
                'db_table': 'inventory_stock_count_line',
                'ordering': ('count_id', 'line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('transfer_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('memo', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='inventory.warehouse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'inventory_stock_transfer',
                'ordering': ('-transfer_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('line_number', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer')),
            ],
            options={
                'db_table': 'inventory_stock_transfer_line',
                'ordering': ('transfer_id', 'line_number', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['organization', 'adjustment_date'], name='inventory_s_organiz_71668b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['organization', 'status'], name='inventory_s_organiz_aa02cd_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='inventory_stock_adjustment_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustmentline',
            constraint=models.CheckConstraint(condition=models.Q(('signed_quantity', 0), _negated=True), name='inventory_stock_adjustment_line_nonzero_qty'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['organization', 'count_date'], name='inventory_s_organiz_9f7a99_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcount',
            index=models.Index(fields=['organization', 'status'], name='inventory_s_organiz_fab576_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockcount',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='inventory_stock_count_unique_reference_per_org'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'transfer_date'], name='inventory_s_organiz_62e2a2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'status'], name='inventory_s_organiz_098b77_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='inventory_stock_transfer_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stocktransfer',
            constraint=models.CheckConstraint(condition=models.Q(('source_warehouse', models.F('destination_warehouse')), _negated=True), name='inventory_stock_transfer_distinct_warehouses'),
        ),
        migrations.AddConstraint(
            model_name='stocktransferline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_stock_transfer_line_qty_positive'),
        ),
    ]
