# Generated by Django 6.0.4 on 2026-04-24 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_soh_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='reversed_by',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverses', to='inventory.stockmovement'),
        ),
    ]
