# Generated by Django 6.0.4 on 2026-04-20 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'catalog_brand',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog.category')),
            ],
            options={
                'db_table': 'catalog_category',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('combo', 'Combo'), ('service', 'Service'), ('digital', 'Digital')], default='standard', max_length=16)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('currency_code', models.CharField(max_length=3)),
                ('barcode_symbology', models.CharField(default='CODE128', max_length=16)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('alert_quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Low-stock threshold. Purely informational; consumed by inventory alerts.', max_digits=18, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalog_product',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='ComboRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='combo_recipe', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_combo_recipe',
            },
        ),
        migrations.CreateModel(
            name='ComboComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.comborecipe')),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appears_in_combos', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_combo_component',
                'ordering': ('recipe_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku_suffix', models.CharField(help_text='Appended to parent code to form full SKU.', max_length=32)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('cost_override', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('price_override', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'db_table': 'catalog_product_variant',
                'ordering': ('product_id', 'sku_suffix'),
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('rate_percent', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'catalog_tax',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.tax'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('conversion_factor', models.DecimalField(decimal_places=8, default=1, help_text='How many base units equal 1 of this unit.', max_digits=18)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('base_unit', models.ForeignKey(blank=True, help_text='Base unit of this family. Self-reference for base units.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='derived_units', to='catalog.unit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
            ],
            options={
                'db_table': 'catalog_unit',
                'ordering': ('code',),
            },
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.unit'),
        ),
        migrations.AddConstraint(
            model_name='brand',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='catalog_brand_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='catalog_category_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='combocomponent',
            constraint=models.UniqueConstraint(fields=('recipe', 'component_product'), name='catalog_combo_component_unique_product_per_recipe'),
        ),
        migrations.AddConstraint(
            model_name='combocomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='catalog_combo_component_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'sku_suffix'), name='catalog_variant_unique_sku_per_product'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='catalog_tax_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.CheckConstraint(condition=models.Q(('rate_percent__gte', 0), ('rate_percent__lte', 100)), name='catalog_tax_rate_in_range'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='catalog_unit_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='catalog_unit_conversion_factor_positive'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'type', 'is_active'], name='catalog_pro_organiz_eee858_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['organization', 'category'], name='catalog_pro_organiz_3684c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='catalog_product_unique_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0), ('price__gte', 0)), name='catalog_product_cost_price_non_negative'),
        ),
    ]
