# Generated by Django 6.0.4 on 2026-04-22 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_inventory_fields'),
        ('finance', '0010_add_audit_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_account',
            field=models.ForeignKey(blank=True, help_text='GL expense account used when purchasing non-inventory items.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_products', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Reorder point quantity. Triggers reorder alert when StockOnHand drops below this.', max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_account',
            field=models.ForeignKey(blank=True, help_text='GL revenue account for sales of this item.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_products', to='finance.account'),
        ),
    ]
