# Generated by Django 6.0.4 on 2026-04-20 01:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('crm', '0001_initial'),
        ('finance', '0002_expensecategory_expense_moneytransfer_payment_and_more'),
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('sale_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('posted', 'Posted'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='draft', max_length=16)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('overpaid', 'Overpaid'), ('refunded', 'Refunded')], db_index=True, default='unpaid', max_length=16)),
                ('currency_code', models.CharField(max_length=3)),
                ('total_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_discount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('lines_tax', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('order_discount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('shipping', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('grand_total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('memo', models.TextField(blank=True, default='')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('biller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='crm.biller')),
                ('created_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='crm.customer')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_sale',
                'ordering': ('-sale_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('uom_code', models.CharField(max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('line_subtotal', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_discount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_tax', models.DecimalField(decimal_places=4, max_digits=18)),
                ('line_total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='catalog.productvariant')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'sales_sale_line',
                'ordering': ('sale_id', 'line_number'),
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'customer', 'sale_date'], name='sales_sale_organiz_2c201d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'status', 'sale_date'], name='sales_sale_organiz_43ceb5_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('organization', 'reference'), name='sales_sale_unique_reference_per_org'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total__gte', 0)), name='sales_sale_grand_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.UniqueConstraint(fields=('sale', 'line_number'), name='sales_sale_line_unique_line_number_per_sale'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sales_sale_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='sales_sale_line_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percent__gte', 0), ('discount_percent__lte', 100), ('tax_rate_percent__gte', 0), ('tax_rate_percent__lte', 100)), name='sales_sale_line_percentages_in_range'),
        ),
    ]
