# Generated by Django 6.0.4 on 2026-04-22 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_add_audit_fields'),
        ('sales', '0005_deliverynote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='creditnote',
            new_name='sales_credi_organiz_482964_idx',
            old_name='sales_cn_org_cust_date_idx',
        ),
        migrations.RenameIndex(
            model_name='creditnote',
            new_name='sales_credi_organiz_799dcd_idx',
            old_name='sales_cn_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customerreceipt',
            new_name='sales_custo_organiz_45688c_idx',
            old_name='sales_rcpt_org_cust_date_idx',
        ),
        migrations.RenameIndex(
            model_name='customerreceipt',
            new_name='sales_custo_organiz_c81a76_idx',
            old_name='sales_rcpt_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='debitnote',
            new_name='sales_debit_organiz_3cdbff_idx',
            old_name='sales_dn_org_cust_date_idx',
        ),
        migrations.RenameIndex(
            model_name='debitnote',
            new_name='sales_debit_organiz_fcd3c0_idx',
            old_name='sales_dn_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='deliverynote',
            new_name='sales_deliv_organiz_149b94_idx',
            old_name='sales_delivnote_org_sale_idx',
        ),
        migrations.RenameIndex(
            model_name='salequotation',
            new_name='sales_sale__organiz_79ee8b_idx',
            old_name='sales_quot_org_cust_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salequotation',
            new_name='sales_sale__organiz_d1e69e_idx',
            old_name='sales_quot_org_status_expiry_idx',
        ),
        migrations.RenameIndex(
            model_name='salesinvoice',
            new_name='sales_invoi_organiz_a59dc4_idx',
            old_name='sales_inv_org_cust_date_idx',
        ),
        migrations.RenameIndex(
            model_name='salesinvoice',
            new_name='sales_invoi_organiz_bd2699_idx',
            old_name='sales_inv_org_status_due_idx',
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='related_invoice',
            field=models.ForeignKey(blank=True, help_text='Invoice this note is issued against. Null for standalone credit notes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='sales.salesinvoice'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='cash / bank_transfer / cheque / card / etc.', max_length=32),
        ),
        migrations.AlterField(
            model_name='customerreceipt',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='due_date',
            field=models.DateField(help_text='Payment due date. Must be ≥ invoice_date.'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1, help_text="Rate of this invoice's currency to the org's functional currency.", max_digits=18),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Sequential number assigned on issue (e.g. INV-2026-0001).', max_length=32),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoiceline',
            name='revenue_account',
            field=models.ForeignKey(blank=True, help_text='Revenue GL account for this line. Falls back to customer.revenue_account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='finance.account'),
        ),
    ]
