# Generated by Django 6.0.4 on 2026-04-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_rename_sales_cn_org_cust_date_idx_sales_credi_organiz_482964_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_address_city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_address_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_address_postal_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_address_state',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='billing_building_number',
            field=models.CharField(blank=True, default='', help_text='Building number — required by ZATCA XML buyer address.', max_length=16),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='payment_terms_text',
            field=models.CharField(blank=True, default='', help_text="Human-readable payment terms printed on the invoice (e.g. 'Net 30', '2/10 Net 30').", max_length=64),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='po_number',
            field=models.CharField(blank=True, default='', help_text="Buyer's purchase-order reference — required for US B2B AP matching.", max_length=64),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address_city',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address_postal_code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='shipping_address_state',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
