# Generated by Django 6.0.4 on 2026-04-24 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_allow_null_category'),
        ('inventory', '0004_fix_soh_unique_constraint'),
        ('sales', '0007_salesinvoice_billing_address_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='salesinvoiceline',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='inventory.warehouse'),
        ),
    ]
