# Generated by Django 6.0.4 on 2026-04-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_salesinvoiceline_product_warehouse'),
        ('tenancy', '0005_organization_accounting_standard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitnote',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Amount settled via CustomerReceipt allocations.', max_digits=18),
        ),
        migrations.CreateModel(
            name='DebitNoteAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('debit_note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='sales.debitnote')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_note_allocations', to='sales.customerreceipt')),
            ],
            options={
                'db_table': 'sales_debit_note_allocation',
                'constraints': [models.UniqueConstraint(fields=('receipt', 'debit_note'), name='sales_dna_unique_receipt_debit_note'), models.CheckConstraint(condition=models.Q(('allocated_amount__gt', 0)), name='sales_dna_allocated_positive')],
            },
        ),
    ]
