# Generated by Django 6.0.4 on 2026-04-25 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_promotions_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerreceipt',
            name='sales_receipt_allocated_not_exceeds_amount',
        ),
        migrations.RemoveConstraint(
            model_name='debitnote',
            name='sales_debit_note_allocated_not_exceeds_total',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='sales_invoice_allocated_not_exceeds_total',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoice',
            name='sales_invoice_exchange_rate_positive',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoiceline',
            name='sales_invoice_line_tax_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoiceline',
            name='sales_invoice_line_subtotal_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='salesinvoiceline',
            name='sales_invoice_line_total_non_negative',
        ),
        migrations.RenameIndex(
            model_name='coupon',
            new_name='sales_coupo_organiz_5ba51e_idx',
            old_name='sales_coupon_organiz_2b6b4c_idx',
        ),
        migrations.RenameIndex(
            model_name='giftcard',
            new_name='sales_gift__organiz_d37527_idx',
            old_name='sales_gift_c_organiz_02d4b8_idx',
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('issued', 'Issued'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('credited', 'Credited')], db_index=True, default='draft', max_length=16),
        ),
    ]
