# Generated by Django 6.0.4 on 2026-04-20 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, default='', max_length=8)),
                ('minor_units', models.PositiveSmallIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'core_currency',
                'ordering': ('code',),
                'constraints': [models.CheckConstraint(condition=models.Q(('minor_units__lte', 4)), name='core_currency_minor_units_lte_4'), models.CheckConstraint(condition=models.Q(('code__regex', '^[A-Z]{3}$')), name='core_currency_code_iso4217_format')],
            },
        ),
    ]
