"""Django model-discovery shim."""
from apps.hr.infrastructure.models import (  # noqa: F401
    Attendance,
    AttendanceStatusChoices,
    Benefit,
    Department,
    Employee,
    EmployeeBenefit,
    EmployeeEvaluation,
    EvaluationRating,
    EvaluationStatus,
    EmployeeTraining,
    Holiday,
    HolidayStatusChoices,
    JobTitle,
    LeaveRequest,
    LeaveRequestStatus,
    LeaveType,
    Payroll,
    TrainingProgram,
    TrainingStatus,
)
