# Generated by Django 6.0.4 on 2026-04-22 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intelligence', '0001_initial'),
        ('tenancy', '0003_organization_phase12_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertevent',
            options={'ordering': ('-triggered_at',)},
        ),
        migrations.AlterModelOptions(
            name='alertrule',
            options={'ordering': ('code',)},
        ),
        migrations.AlterModelOptions(
            name='anomalycase',
            options={'ordering': ('-detected_at', '-score')},
        ),
        migrations.AlterModelOptions(
            name='assistantquery',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='auditcase',
            options={'ordering': ('-opened_at',)},
        ),
        migrations.AlterModelOptions(
            name='duplicatematch',
            options={'ordering': ('-similarity_score', '-id')},
        ),
        migrations.AlterModelOptions(
            name='insightsnapshot',
            options={'ordering': ('-generated_at',)},
        ),
        migrations.AlterModelOptions(
            name='kpivalue',
            options={'ordering': ('-calculated_at',)},
        ),
        migrations.AlterModelOptions(
            name='riskscore',
            options={'ordering': ('-calculated_at',)},
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='intelligenc_organiz_224c13_idx',
            old_name='intel_alert_ev_org_status',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='intelligenc_organiz_b1bfdb_idx',
            old_name='intel_alert_ev_org_rule',
        ),
        migrations.RenameIndex(
            model_name='alertevent',
            new_name='intelligenc_organiz_f2eb17_idx',
            old_name='intel_alert_ev_org_src',
        ),
        migrations.RenameIndex(
            model_name='anomalycase',
            new_name='intelligenc_organiz_d81e1d_idx',
            old_name='intel_acase_org_status_sev',
        ),
        migrations.RenameIndex(
            model_name='anomalycase',
            new_name='intelligenc_organiz_4c351a_idx',
            old_name='intel_acase_org_src',
        ),
        migrations.RenameIndex(
            model_name='anomalycase',
            new_name='intelligenc_organiz_3165b3_idx',
            old_name='intel_acase_org_type_det',
        ),
        migrations.RenameIndex(
            model_name='assistantquery',
            new_name='intelligenc_organiz_051b51_idx',
            old_name='intel_assistant_org_user',
        ),
        migrations.RenameIndex(
            model_name='auditcase',
            new_name='intelligenc_organiz_83a52a_idx',
            old_name='intel_audit_org_status_sev',
        ),
        migrations.RenameIndex(
            model_name='auditcase',
            new_name='intelligenc_organiz_4d7395_idx',
            old_name='intel_audit_org_src',
        ),
        migrations.RenameIndex(
            model_name='auditcase',
            new_name='intelligenc_organiz_eaa8a9_idx',
            old_name='intel_audit_org_type_status',
        ),
        migrations.RenameIndex(
            model_name='duplicatematch',
            new_name='intelligenc_organiz_fbdd50_idx',
            old_name='intel_dup_org_entity_status',
        ),
        migrations.RenameIndex(
            model_name='duplicatematch',
            new_name='intelligenc_organiz_ce4d0b_idx',
            old_name='intel_dup_org_left',
        ),
        migrations.RenameIndex(
            model_name='duplicatematch',
            new_name='intelligenc_organiz_295188_idx',
            old_name='intel_dup_org_right',
        ),
        migrations.RenameIndex(
            model_name='insightsnapshot',
            new_name='intelligenc_organiz_cea159_idx',
            old_name='intel_insight_org_type_period',
        ),
        migrations.RenameIndex(
            model_name='kpivalue',
            new_name='intelligenc_organiz_161af0_idx',
            old_name='intel_kpi_org_code_period',
        ),
        migrations.RenameIndex(
            model_name='riskscore',
            new_name='intelligenc_organiz_f469d2_idx',
            old_name='intel_risk_org_entity_calc',
        ),
        migrations.RenameIndex(
            model_name='riskscore',
            new_name='intelligenc_organiz_bb1ace_idx',
            old_name='intel_risk_org_level_calc',
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='context_json',
            field=models.JSONField(default=dict, help_text='Snapshot of the values that triggered the alert.'),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='condition_json',
            field=models.JSONField(default=dict, help_text='Structured condition evaluated by the alert service.'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='target_role',
            field=models.CharField(blank=True, default='', help_text='Role that receives this alert. Empty = all finance roles.', max_length=64),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='evidence_json',
            field=models.JSONField(default=dict, help_text='Raw evidence: comparison values, thresholds, context.'),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0–100 normalized anomaly score.', max_digits=6),
        ),
        migrations.AlterField(
            model_name='anomalycase',
            name='source_type',
            field=models.CharField(db_index=True, help_text="e.g. 'purchases.purchaseinvoice'", max_length=64),
        ),
        migrations.AlterField(
            model_name='assistantquery',
            name='citations_json',
            field=models.JSONField(default=list, help_text='List of data sources/selectors consulted.'),
        ),
        migrations.AlterField(
            model_name='assistantquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='assistantquery',
            name='latency_ms',
            field=models.PositiveIntegerField(blank=True, help_text='End-to-end response time in milliseconds.', null=True),
        ),
        migrations.AlterField(
            model_name='assistantquery',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='case_number',
            field=models.CharField(db_index=True, help_text='Human-readable sequential number (AC-2026-0001).', max_length=32),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='auditcase',
            name='signal_type',
            field=models.CharField(blank=True, default='', help_text="e.g. 'intelligence.anomalycase'", max_length=64),
        ),
        migrations.AlterField(
            model_name='duplicatematch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='duplicatematch',
            name='duplicate_reason',
            field=models.TextField(help_text='Which fields matched and how.'),
        ),
        migrations.AlterField(
            model_name='duplicatematch',
            name='entity_type',
            field=models.CharField(db_index=True, help_text="e.g. 'purchases.purchaseinvoice'", max_length=64),
        ),
        migrations.AlterField(
            model_name='duplicatematch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='duplicatematch',
            name='similarity_score',
            field=models.DecimalField(decimal_places=4, help_text='0.0000–1.0000', max_digits=5),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='content',
            field=models.TextField(help_text='Markdown narrative text.'),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='data_snapshot_json',
            field=models.JSONField(default=dict, help_text='Raw metric values used to generate the narrative.'),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='generated_for_period',
            field=models.CharField(help_text='YYYY-MM identifying the period this covers.', max_length=8),
        ),
        migrations.AlterField(
            model_name='insightsnapshot',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='kpivalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='kpivalue',
            name='metadata_json',
            field=models.JSONField(default=dict, help_text='Numerator, denominator, formula used.'),
        ),
        migrations.AlterField(
            model_name='kpivalue',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='contributing_factors_json',
            field=models.JSONField(default=list, help_text='Ordered list of factor dicts (factor, weight, explanation).'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.organization'),
        ),
        migrations.AlterField(
            model_name='riskscore',
            name='score',
            field=models.DecimalField(decimal_places=2, help_text='0.00–100.00', max_digits=5),
        ),
    ]
